version: "3"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sh@dow
    ports:
      - 127.0.0.1:5432:5432