# Generated by Django 3.1.5 on 2021-01-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210117_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('username', models.CharField(max_length=30)),
                ('image_id', models.CharField(max_length=512)),
                ('image_tag', models.CharField(max_length=216)),
                ('image_name', models.CharField(default='1', max_length=216)),
                ('inside_port', models.CharField(max_length=128)),
                ('outside_port', models.CharField(max_length=128)),
                ('contain', models.CharField(max_length=512)),
                ('status', models.CharField(default='1', max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='dockername',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
