# Generated by Django 3.1.5 on 2021-01-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210117_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DockerName',
            new_name='TopicName',
        ),
    ]
