# Generated by Django 3.1.5 on 2021-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210118_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicname',
            name='inside_port',
            field=models.CharField(default='80', max_length=126),
        ),
    ]
