# Generated by Django 3.1.5 on 2021-01-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210118_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicname',
            old_name='images_tag',
            new_name='image_tag',
        ),
    ]
