# Generated by Django 3.1.5 on 2021-01-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210118_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicname',
            name='image_tag',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
