# Generated by Django 3.1.5 on 2021-01-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210118_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='地址')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户')),
                ('score', models.IntegerField(default=0)),
                ('image_name', models.CharField(default='default', max_length=30)),
                ('category', models.CharField(max_length=1024)),
                ('type', models.CharField(default='docker', max_length=32)),
                ('answer', models.BooleanField(default=False)),
            ],
        ),
    ]
