# Generated by Django 3.1.5 on 2021-01-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210118_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containers',
            old_name='image_name',
            new_name='topic_name',
        ),
    ]
