# Generated by Django 3.1.5 on 2021-01-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210118_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolver',
            old_name='address',
            new_name='image_tag',
        ),
        migrations.RenameField(
            model_name='topicname',
            old_name='images_status',
            new_name='image_status',
        ),
    ]
