# Generated by Django 3.1.5 on 2021-01-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210118_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='topicname',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterField(
            model_name='topicname',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='backend.category', verbose_name='镜像分类'),
        ),
        migrations.AlterField(
            model_name='topicname',
            name='image_tag',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
