# Generated by Django 3.1.5 on 2021-01-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210125_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='flag_string',
            field=models.CharField(default='1', max_length=128, null=True),
        ),
    ]
