# Generated by Django 3.1.5 on 2021-01-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210125_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolver',
            name='address',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
